com:
  mqtt:
    username: admin
    password: public
    url: tcp://192.168.80.128:1883
    inbound:
      clientId: emq-client-id-subscribe
      topic: topic1,topic2
      completionTimeout: 60
    outbound:
      clientId: emq-client-id-publisher
      topic: topic1
server:
  port: 7000